
# Site settings
title: Jiayi Wang
name: Jiayi Wang
subtitle:  MEM Student at Dartmouth College
email: jiayi.wang.th@dartmouth.edu
description: >
   
baseurl: ""
url: "https://wangjiayi0131.github.io/"
github_username:  wangjiayi0131
disqus_baseurl: "https://wangjiayi0131.github.io/"
disqus_shortname: https-wangjiayi0131-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Jiayi Wang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: wangjiayi0131
    url: https://github.com/wangjiayi0131
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Jiayi Wang
    url: https://www.linkedin.com/in/jiayiwang0131
    desc: Connect with me on LinkedIn
    share: true
