
# Site settings
title: Mengyuan Li
name: Mengyuan Li
subtitle:  PhD Student at TUDelft
email: mli10@tudelft.nl
description: >
   
baseurl: ""
url: "https://uniquelmy.github.io/MengyuanLi.github.io/"
github_username:  uniquelmy
disqus_baseurl: "https://uniquelmy.github.io/MengyuanLi.github.io/"
disqus_shortname: https-uniquelmy-github-io-MengyuanLi-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Mengyuan Li"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: twitter
    icon: twitter
    username: Mengyuan Li
    url: https://twitter.com/lmngyun59829024
    desc: Connect with me on twitter
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Mengyuan Li
    url: https://www.linkedin.com/in/%E6%A2%A6%E5%9B%AD-%E6%9D%8E-4934b7262/
    desc: Connect with me on LinkedIn
    share: true
